### ISSUE TITLE
Lack of HTTP method on actions causing an error when trying to view Swagger

### ISSUE THREAD

**Issue by adayinthelifeofapro** [GeekInTheNorth/Stott.Security.Optimizely#186]
As shown below, to be able to view a swagger document, all actions need to be decorated with an explicit HttpMethod

![image](https://github.com/GeekInTheNorth/Stott.Security.Optimizely/assets/108930057/f46da986-6dde-44a0-bb04-86a6b6a269c4)

**Comment by adayinthelifeofapro** [comment]
@GeekInTheNorth many thanks for merging this in so quickly, very much appreciated 👍

**Comment by GeekInTheNorth** [comment]
@adayinthelifeofapro  No worries mate, I've credited you on the release notes withing the discussions section too :)
