### ISSUE TITLE
Not valid sources for ws:, .io, and .co

### ISSUE THREAD

**Issue by lunchin** [GeekInTheNorth/Stott.Security.Optimizely#190]
A couple sources I am trying to add are not allowed.  I am trying to add ws: for connect-src and is not allowed due to validation error.  I also am not allowed to add domain names ending in .co or .io

**Comment by GeekInTheNorth** [comment]
Hello @lunchin 

I've made some changes to loosen the validation to allow for .co and .io domains and to allow ws: and wss: schema.  I'll pack you up a hotfix later today.

Regards,
Mark

**Comment by GeekInTheNorth** [comment]
@lunchin packages have just been uploaded as 2.4.2 to nuget.org and api.nuget.optimizely.com

**Comment by lunchin** [comment]
thank you
