### ISSUE TITLE
Add the ability to Import/Export settings

### ISSUE THREAD

**Issue by GeekInTheNorth** [GeekInTheNorth/Stott.Security.Optimizely#196]
Add the ability to export and import CSP settings from one environment to the next.

Requirements:
- A new tab for "Advanced" options
  - A new "Export Settings" CTA that will produce a JSON or XML file containing all of the configuration
  - A new "Import Settings" CTA that will consume a JSON or XML file and will remove all existing settings to be replaced by the configuration being imported.
  - After import, CSP should be set to "Report Only Mode" in case users end up locked out.

**Comment by breizh22** [comment]
That is exactly what we are gonna need, that is either import/export or set all settings via code or configuration.

**Comment by GeekInTheNorth** [comment]
Hello @breizh22 

I won't be supporting configuration as code directly as that goes against the point of the module.  But there are some approaches you can use right now to fast track your CSP between environments.

- Use the External Allow List with a preset list of sources and allowed directives.  When the CSP report is received, it will check this allow list (which it caches) and will self heal the CSP.
- Use a standard Optimizely Migration Step and consume the following during startup to pre-populate your CSP:
  - ICspPermissionService
  - ICspSettingsService
  - ICspSandboxService
- Define a separate DB for the Security module in Startup.cs
  - This allows you to keep Security Configuration separate from the CMS in terms of the DB
  - You can restore the DB you use for Prep in place of the one you use for Prod ahead of deployment.

I'll be aiming for a simple Json Import / Export.  But it will take some time to build this functionality.

**Comment by breizh22** [comment]
"Use a standard Optimizely Migration Step and consume the following during startup to pre-populate your CSP:
ICspPermissionService
ICspSettingsService
ICspSandboxService"

I'm not sure what you mean by that, migration step to save new report url doesn't work for me.

**Comment by GeekInTheNorth** [comment]
Hi @breizh22 

Optimizely CMS will action a class that inherits MigrationStep on startup of the solution.  Its an abstract class that is normally used for managing the refactoring of content types.  But you can do much more with them.

In this case you can pre-populate the module configuration within a Migration Step which consumes the modules services/repositories and you'd just have to make sure it runs only once.

```
public class SetUpSecurityMigrationStep: MigrationStep
{
   private readonly ICspSettingsService _cspSettingsService;

    public override void AddChanges()
    {
        _cspSettingsService.SaveAsync(new CspSettingsModel
        {
             IsEnabled = true,
             IsReportOnly = true,
             UseInternalReporting = false,
             UseExternalReporting = true,
             ExternalReportToUrl = "https://www.example.com",
        },
       "System").GetAwaiter().GetResult();
    }
}
```

I will add that I've started work on the Import / Export functionality already.  I don't want to commit to any specific date for delivery as I maintain this outside of my day job.

Regards,
Mark

**Comment by GeekInTheNorth** [comment]
Hello @breizh22,

This is now live in version 2.6.0, you can read more here: https://github.com/GeekInTheNorth/Stott.Security.Optimizely/discussions/207
