### ISSUE TITLE
A possible object cycle was detected

### ISSUE THREAD

**Issue by adayinthelifeofapro** [GeekInTheNorth/Stott.Security.Optimizely#215]
I am seeing this error message which seems to be stopping any searches via Optimizely S&N from working correctly, is this something you have seen before at all??

_A possible object cycle was detected. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 32. Consider using ReferenceHandler.Preserve on JsonSerializerOptions to support cycles. Path: $.Items.Image.Property.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Locate._ 

![image](https://github.com/GeekInTheNorth/Stott.Security.Optimizely/assets/108930057/c678a9b4-d1b1-4d89-a36b-d346d51efcf9)

**Comment by GeekInTheNorth** [comment]
@adayinthelifeofapro Can you provide a full stack trace.  Middlewares can obfuscate the original error location.  There is no object  within my code base that had a property of items.Image.Property.Parent.Parent...Locate so it's likely some thing within your own code or dependencies that is erring.  My middleware catches any exception and logs it out, but the pipeline of middlewares are passed into each other.

**Comment by adayinthelifeofapro** [comment]
yes, you are indeed correct, ignore me, upon debugging it became clear that this is nothing to do with the security module.
