### ISSUE TITLE
Deployment to Integration fails after adding this addon

### ISSUE THREAD

**Issue by huseinshaikh** [GeekInTheNorth/Stott.Security.Optimizely#257]
Hi, Is any one facing deployment failing issue? everything works great in my local but when I merge the code to my Integration branch and triggers a deploy it get's fail.

Getting this message in logs
System.ArgumentException: Unable to find a module by assembly 'Stott.Security.Optimizely, Version=2.8.2.0, Culture=neutral, PublicKeyToken=null' (Parameter 'moduleAssembly')",

We are on CMS12 .net8

**Comment by GeekInTheNorth** [comment]
Hello @huseinshaikh 

It sounds like you're missing the `modules/_protected/Stott.Security.Optimizely/module.config` file in your package output.

I have pipelines in ADO and GitHub deploying .NET 8 and .NET 6 versions without an issue or any special actions being required.  But I've had another feedback before where they had to commit that `module.config` into source control.

**Comment by GeekInTheNorth** [comment]
Closing due to no response
